apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-db
  namespace: docker-testing
  labels:
    app: mi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-db
  template:
    metadata:
      labels:
        app: mi-db
    spec:
      containers:
        - name: mi-db
          image: ${ECR_DB_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: db-storage
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: db-storage
          emptyDir: {}
